services:
  db:
    image: postgres:17
    restart: unless-stopped
    container_name: dev-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sso-oidc-dev
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
