services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  # redis:
  #   image: redis:latest
  #   networks:
  #     - my_network

  rust_web_server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      # - redis
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8080:8080"
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
