services:
  db:
    image: postgres:17
    restart: unless-stopped
    container_name: dev-postgres
    ports:
      - "5432:5432"
    env_file: .env.dev
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ${DATABASE_URL}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  sqlx-cli:
    build:
      context: .
      dockerfile: Dockerfile.sqlx-cli
    depends_on:
      db:
        condition: service_healthy
    env_file: .env.dev
    volumes:
      - .:/app
    profiles:
      - tools

volumes:
  pg_data:
  redis-data:
