applications:
  - id: "660e8400-e29b-41d4-a716-446655440002"
    tenant_id: "550e8400-e29b-41d4-a716-446655440003"
    name: "NexusFlow CRM"
    client_id: "nexusflow_client_001"
    client_secret: "nexusflow_secret_2024"
    uri: "http://localhost:5555"
    redirect_uris:
      - "https://www.nexusflow.com/auth/callback"
      - "http://localhost:5555/dashboard"
    post_logout_redirect_uris:
      - "https://www.nexusflow.com/logout"

  - id: "660e8400-e29b-41d4-a716-446655440003"
    tenant_id: "550e8400-e29b-41d4-a716-446655440003"
    name: "DataVault Portal"
    client_id: "datavault_client_001"
    client_secret: "datavault_secret_2024"
    uri: "http://localhost:3000"
    redirect_uris:
      - "http://localhost:3000/site"
    post_logout_redirect_uris:
      - "https://localhost:3000/logout"

  - id: "660e8400-e29b-41d4-a716-446655440004"
    tenant_id: "550e8400-e29b-41d4-a716-446655440004"
    name: "ChronoMail"
    client_id: "chronomail_client_001"
    client_secret: "chronomail_secret_2024"
    uri: "https://mail.chronotech.com"
    redirect_uris:
      - "https://mail.chronotech.com/auth/callback"
    post_logout_redirect_uris:
      - "https://mail.chronotech.com/logout"

  - id: "660e8400-e29b-41d4-a716-446655440005"
    tenant_id: "550e8400-e29b-41d4-a716-446655440005"
    name: "Aether Compute Console"
    client_id: "aether_compute_client_001"
    client_secret: "aether_compute_secret_2024"
    uri: "https://console.aetherdynamics.com"
    redirect_uris:
      - "https://console.aetherdynamics.com/auth/callback"
    post_logout_redirect_uris:
      - "https://console.aetherdynamics.com/logout"