# User 1
# # email: testuser1@example.com
# # password: password123

# User 2
# # email: testuser2@example.com
# # password: supersecure!
users:
  - id: "11111111-1111-1111-1111-111111111111"
    tenant_id: "550e8400-e29b-41d4-a716-446655440003"
    username: "testuser1"
    email: "testuser1@example.com"
    password_hash: "$argon2id$v=19$m=19456,t=2,p=1$CiWT/iNz+QUPHXUB7KAyNA$XR95n8k+973UfW7L7saNd8XEAYxnHJ6Q6ynC+4LhHgA"
    is_active: true

  - id: "22222222-2222-2222-2222-222222222222"
    tenant_id: "550e8400-e29b-41d4-a716-446655440004"
    username: "testuser2"
    email: "testuser2@example.com"
    password_hash: "$argon2id$v=19$m=19456,t=2,p=1$sYNS9Hql3Bd6j16iax9gNg$Mnmv9x2T2IAtDIHwO+QE13oB1SsMQhc8NTJAST71+bQ"
    is_active: true
